id: A4A82C487
title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
type: translation
pechas:
- I98F67118
- I8F85785F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:04.690737
  last_modified_at: 2023-01-04 12:45:04.690763
  collections:
  - Jokyab Pema Trinlé Nyingpo
  - Works of Tibetan Masters
alignment_to_base:
  I98F67118/34C4: 20E9
  I8F85785F/9B0A: 20E9
